meta-swupd: swupd-image.bbclass: fix special code path for "no swupd bundles"
When there are no additional bundles, there's no need to create a
separate "mega bundle" rootfs and several copy operations can be
skipped because the rootfs created for the main image recipe already
represents the final content. That particular code path is taken for
SWUPD_BUNDLES = "".

In some functions, the special handling of that configuration was missing,
leading to:

Exception: subprocess.CalledProcessError: Command 'tar --xattrs --xattrs-include='' -cf - -C None -p . | tar -p --xattrs --xattrs-include='' -xf - -C .../ostro-image-swupd/1.0-r0/rootfs' returned non-zero exit status 2

Fixes: IOTOS-1725

(From meta-swupd rev: b51f7d56101a4b094170bac42667291ee177168a)

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>