meta-oic: iotivity-sensorboard: Use regular LDFLAGS variable and pthread
Without this change and error on linkage is displayed :

  ld: observer.o: undefined reference to symbol
  'pthread_create@@GLIBC_2.2.5' libpthread.so.0: error adding
  symbols: DSO missing from command line collect2: error: ld
  returned 1 exit status

  Also YOCTOLDFLAGS are replaced with regular LDFLAGS,
  to use quality check.

Without this, QA check is failing and this message is reported:

  do_package_qa: QA Issue: No GNU_HASH in the elf binary:

(From meta-oic rev: 83a8d36db5ba0fd9dea2daf0e16d286727aaebf8)

Signed-off-by: Kishen Maloor <kishen.maloor@intel.com>