meta-yocto: poky-tiny: Set native DISTRO_FEATURES
This should resolve failures like:

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'libxext-native' (but virtual:native:/home/pokybuild/yocto-autobuilder/yocto-worker/poky-tiny/build/meta/recipes-devtools/qemu/qemu_2.1.0.bb DEPENDS on or otherwise requires it)
ERROR: libxext-native was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
NOTE: Runtime target 'qemu-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['qemu-native', 'libxext-native']

(From meta-yocto rev: 171e3df2ddfe8b30657fd5957f2fe1bc3fb3648b)

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>