meta-openembedded: liboauth: Add missing OpenSSL build dependency
Fixes:

| liboauth-1.0.3/src/hash.c:363:26: fatal error: openssl/hmac.h:
|  No such file or directory

(From meta-openembedded rev: 57d90f372912efc00499983c628daab9a38071b2)

Signed-off-by: Jacob Kroon <jacob.kroon@mikrodidakt.se>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>