meta-openembedded: terminus-font, ttf*: exclude fontconfig dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: terminus-font different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'terminus-fontterminus-font_4.38.bb.do_package', 'terminus-fontterminus-font_4.38.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'terminus-fontterminus-font_4.38.bb.do_package', 'terminus-fontterminus-font_4.38.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-arphic-uming different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-arphic-uming_20080216.bb.do_package', 'ttf-fontsttf-arphic-uming_20080216.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-arphic-uming_20080216.bb.do_package', 'ttf-fontsttf-arphic-uming_20080216.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-dejavu different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-dejavu_2.35.bb.do_package', 'ttf-fontsttf-dejavu_2.35.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-dejavu_2.35.bb.do_package', 'ttf-fontsttf-dejavu_2.35.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-droid different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-droid_git.bb.do_package', 'ttf-fontsttf-droid_git.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-droid_git.bb.do_package', 'ttf-fontsttf-droid_git.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-gentium different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-gentium_1.02.bb.do_package', 'ttf-fontsttf-gentium_1.02.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-gentium_1.02.bb.do_package', 'ttf-fontsttf-gentium_1.02.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-hunkyfonts different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-hunkyfonts_0.3.0.bb.do_package', 'ttf-fontsttf-hunkyfonts_0.3.0.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-hunkyfonts_0.3.0.bb.do_package', 'ttf-fontsttf-hunkyfonts_0.3.0.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-inconsolata different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-inconsolata_20100526.bb.do_package', 'ttf-fontsttf-inconsolata_20100526.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-inconsolata_20100526.bb.do_package', 'ttf-fontsttf-inconsolata_20100526.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-liberation different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-liberation_0.2.bb.do_package', 'ttf-fontsttf-liberation_0.2.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-liberation_0.2.bb.do_package', 'ttf-fontsttf-liberation_0.2.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-mplus different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-mplus_027.bb.do_package', 'ttf-fontsttf-mplus_027.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-mplus_027.bb.do_package', 'ttf-fontsttf-mplus_027.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-sazanami different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-sazanami_20040629.bb.do_package', 'ttf-fontsttf-sazanami_20040629.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-sazanami_20040629.bb.do_package', 'ttf-fontsttf-sazanami_20040629.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-tlwg different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-tlwg_0.6.1.bb.do_package', 'ttf-fontsttf-tlwg_0.6.1.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-tlwg_0.6.1.bb.do_package', 'ttf-fontsttf-tlwg_0.6.1.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-ubuntu-font-family different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-ubuntu-font-family_0.80.bb.do_package', 'ttf-fontsttf-ubuntu-font-family_0.80.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-ubuntu-font-family_0.80.bb.do_package', 'ttf-fontsttf-ubuntu-font-family_0.80.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

ERROR: ttf-wqy-zenhei different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-wqy-zenhei_0.9.45.bb.do_package', 'ttf-fontsttf-wqy-zenhei_0.9.45.bb.do_packagedata'] to ['fontconfigfontconfig_2.11.94.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'ttf-fontsttf-wqy-zenhei_0.9.45.bb.do_package', 'ttf-fontsttf-wqy-zenhei_0.9.45.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 736c4f55866f0d3dc2df677413ac50d8
 changed to
openembedded-core/meta/recipes-graphics/fontconfig/fontconfig_2.11.94.bb.do_packagedata with hash 44d2223000ef1b272de20bb6212e20e2
Hash for dependent task fontconfigfontconfig_2.11.94.bb.do_packagedata changed from 736c4f55866f0d3dc2df677413ac50d8 to 44d2223000ef1b272de20bb6212e20e2

(From meta-openembedded rev: 1f96c7d8ce6e18a2c87a180a94afc179f407c5ab)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>