meta-openembedded: libmicrohttpd: Update to 0.9.34
This update fixes the following build error:

,----[ Build error ]
| ...
| .../libmicrospdy.so: undefined reference to `SSL_get_error'
| .../libmicrospdy.so: undefined reference to `SSL_write'
| .../libmicrospdy.so: undefined reference to `SSL_free'
| ...
`----

Reported-by: Prabhu Sundararaj <prabhu.sundararaj@freescale.com>
(From meta-openembedded rev: 4f94d47ff55ed3ca9cd8efdcf165a7d85835b7ad)

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>