meta-openembedded: zabbix: set MACHINE_ARCH, because it depends on MACHINE specific KERNEL_VERSION
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: zabbix different signature for task do_configure.sigdata between qemux86copy and qemux86
basehash changed from 2b2cdeb8b36ed130bf28374a5b6d2e4d to 624cc1888e50c4509679c829a906af03
Variable MACHINE value changed from 'qemux86copy' to 'qemux86'

(From meta-openembedded rev: 2200a08dc60486017e59c1950fd3138f79e21030)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>