meta-openembedded: smbnetfs: using PKG_CHECK_MODULES to found headers and libraries for smbclient
After samba was upgraded to 4.x, headers of smbclient were installed into include/samba-4.0/,
so we should using PKG_CHECK_MODULES to found headers and libraries for smbclient to avoid
error as below.

 ${WORKDIR}/git/src/samba.c
   | smbnetfs/git-r0/git/src/smb_conn_srv.c:12:26: fatal error: libsmbclient.h: No such file or directory  #include <libsmbclient.h>
   |                           ^
   | compilation terminated.
   | make[2]: *** [smb_conn_srv.o] Error 1
   | make[2]: *** Waiting for unfinished jobs....

(From meta-openembedded rev: 3659908852b0241ecdce0a53423d7118763c1485)

Signed-off-by: Bian Naimeng <biannm@cn.fujitsu.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>