meta-openembedded: compat-wireless: upgrade and fixup
* use INC_PR
* fix RDEPENDS
* use normal PV
* move checksums from .inc to .bb
* upgrade, because old version fails to build with a lot of errors like this:
  compat-wireless-3.5-rc5-1/include/linux/compat-3.5.h:102:8: error: redefinition of 'struct tc_fq_codel_xstats'
* 3.5.4-1, 3.6.8-1 can failed when kernel option is missing:
  | compat-wireless-all/3.5.4-r1.0/compat-wireless-3.5.4-1/drivers/net/ethernet/broadcom/b44.c:2342:2:
    error: implicit declaration of function 'ssb_pcihost_register' [-Werror=implicit-function-declaration]
  | cc1: some warnings being treated as errors

(From meta-openembedded rev: 13d3e76d99dfcf53347d76b95ebff5ac7292f347)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>