meta-openembedded: python-cython: add RDEPENDS on some required python modules
python-distribute:
    File "/usr/bin/cython", line 5, in <module>
    ImportError: No module named pkg_resources

python-netserver:
    File "_tempita.py", line 34, in init Cython.Tempita._tempita
    ImportError: No module named cgi

python-subprocess:
    File "/usr/lib/python2.7/site-packages/Cython/Debugger/Cygdb.py", line 19, in <module>
    ImportError: No module named subprocess

python-shell:
    File "/usr/lib/python2.7/site-packages/Cython/Debugger/Cygdb.py", line 16, in <module>
    ImportError: No module named glob

(From meta-openembedded rev: fea3840ee5829afc4b159c81341366e47e4d6959)

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>