meta-openembedded: Remove toolchain-layer
Just including the toolchain-layer in a bblayers.conf results in:
  ERROR: ExpansionError during parsing .../meta-oe/toolchain-layer/recipes-devtools/gcc/gcc-crosssdk_4.6.bb: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: SRCREV was used yet no valid SCM was found in SRC_URI

Since there is no maintainer, remove it from meta-openembedded.

(From meta-openembedded rev: 5a5ec1c0607466d0369170c7a3e25ca92d51ca1c)

Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>