meta-openembedded: task-xfce-base: add thunar-volman
This fixes:

ERROR: There is a comment on line 34 of file /OE/tentacle/sources/meta-openembedded/meta-xfce/recipes-xfce/tasks/task-xfce-base.bb (#    thunar-volman \) which is in the middle of a multiline expression.
Bitbake used to ignore these but no longer does so, please fix your metadata as errors are likely as a result of this change.

(From meta-openembedded rev: cc791b00ca980373402a8487b7aff4c2cf45c390)

Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>
Acked-by: Andreas Müller <schnitzeltony@gmx.de>