meta-openembedded: netmap: set MACHINE_ARCH, because it depends on MACHINE_ARCH netmap-modules
* it's also using MACHINE specific variables like:
  STAGING_KERNEL_DIR. STAGING_KERNEL_BUILDDIR
* drop suspicious:
  do_fetch[depends] += "netmap-modules:do_fetch"
  fetcher should use .lock files to prevent updating the same repository
  in parallel
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: netmap different signature for task do_configure.sigdata between qemux86copy and qemux86
basehash changed from 748eae270193023d79f7d6a69aa1b8d2 to 9267873ef5fa4474d5f60fc79044ab64
Variable MACHINE value changed from 'qemux86copy' to 'qemux86'

(From meta-openembedded rev: f6a3cd4dcd1654a953c505ff779090717314871a)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>