meta-openembedded: Revert "systemd.bbclass: Dont check for multilib and change for nativesdk renaming"
This triggers:

ERROR: Nothing RPROVIDES 'connman-systemd' (but /OE/tentacle/sources/meta-angstrom/recipes-images/angstrom/systemd-image.bb RDEPENDS on or otherwise requires it)

This reverts commit cbac8756e815c3f141cebf6d2e6875400980a4f9.

From meta-openembedded rev: aff5f48fb89ae8427cbbd5341f3bd1d4e43582f6