meta-openembedded: minini: fix build when SECURITY_CFLAGS includes -pie -fpie
Separating compile and link steps avoids build errors when
security_flags.inc is used:

  | DEBUG: Executing shell function do_compile
  | ../sysdeps/i386/start.S:98: error: undefined reference to 'main'
  | collect2: error: ld returned 1 exit status

(From meta-openembedded rev: 38f86f841b92d65419af96c8492e3fa49bf3c125)

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>