meta-intel: meta-emenlow: unset preferred providers for virtual/libgles[12]
The recent changes to enable GLES/EGL in mesa-dri have caused emenlow to fail:

ERROR: Trying to resolve runtime dependency libglu resulted in conflicting PREFERRED_PROVIDER entries being found.
The providers found were: ['/srv/home/pokybuild/yocto-autobuilder/yocto-slave/emenlow/build/yocto/meta-intel/meta-emenlow/recipes-graphics/xpsb-glx/xpsb-glx_0.18.bb', '/srv/home/pokybuild/yocto-autobuilder/yocto-slave/emenlow/build/meta/recipes-graphics/mesa/mesa-dri_8.0.4.bb']
The PREFERRED_PROVIDER entries resulting in this conflict were: ['PREFERRED_PROVIDER_mesa-dri = xpsb-glx', 'PREFERRED_PROVIDER_virtual/libgles1 = mesa-dri']

Because emenlow's xpsb-glx contains mesa, it needs to entirely replace
mesa-dri. We'd normally set virtual/libgles1 and virtual/libgles2 to xpsb-glx
but these drivers don't build the GLES libraries so that would be a lie.

So, unset the preferred provider entries so that bitbake doesn't look at
mesa-dri at all.

(From meta-intel rev: 1ef6cd26cabe46d9ceaa0d257bf7d690a0592e7c)

Signed-off-by: Tom Zanussi <tom.zanussi@intel.com>