meta-openembedded: xserver-common, xserver-nodm-init: drop allarch, depends on couple TUNE_PKGARCH recipes
* xmodmap xrandr xdpyinfo fbset xinput-calibrator xinit
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: xserver-common different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['fbsetfbset_2.1.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'xinput-calibratorxinput-calibrator_git.bb.do_packagedata', 'xorg-appxdpyinfo_1.3.2.bb.do_packagedata', 'xorg-appxmodmap_1.0.9.bb.do_packagedata', 'xorg-appxrandr_1.4.3.bb.do_packagedata', 'xserver-commonxserver-common_1.34.bb.do_package', 'xserver-commonxserver-common_1.34.bb.do_packagedata'] to ['fbsetfbset_2.1.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'xinput-calibratorxinput-calibrator_git.bb.do_packagedata', 'xorg-appxdpyinfo_1.3.2.bb.do_packagedata', 'xorg-appxmodmap_1.0.9.bb.do_packagedata', 'xorg-appxrandr_1.4.3.bb.do_packagedata', 'xserver-commonxserver-common_1.34.bb.do_package', 'xserver-commonxserver-common_1.34.bb.do_packagedata']
meta-openembedded/meta-oe/recipes-support/fbset/fbset_2.1.bb.do_packagedata with hash ce7c4dca0cda8d720fd74d2bd1d66fbb
 changed to
meta-openembedded/meta-oe/recipes-support/fbset/fbset_2.1.bb.do_packagedata with hash a232e1b9ce0275f2a989d74cc7053a84
openembedded-core/meta/recipes-graphics/xinput-calibrator/xinput-calibrator_git.bb.do_packagedata with hash d688277915e6c9d7e41a00d941dfc590
 changed to
openembedded-core/meta/recipes-graphics/xinput-calibrator/xinput-calibrator_git.bb.do_packagedata with hash 9d440e251880adaaa743aecabc86ae36
openembedded-core/meta/recipes-graphics/xorg-app/xdpyinfo_1.3.2.bb.do_packagedata with hash 8122f0ff1b1e47cca2ddb162075e7f44
 changed to
openembedded-core/meta/recipes-graphics/xorg-app/xdpyinfo_1.3.2.bb.do_packagedata with hash 4d9acf7ce5cfa462d66b04b2bf14b851
openembedded-core/meta/recipes-graphics/xorg-app/xmodmap_1.0.9.bb.do_packagedata with hash 9d3e895ec99bf9e9204aa619238e4cc8
 changed to
openembedded-core/meta/recipes-graphics/xorg-app/xmodmap_1.0.9.bb.do_packagedata with hash f4a63b5a780ad1eee027ec5c41d1698b
openembedded-core/meta/recipes-graphics/xorg-app/xrandr_1.4.3.bb.do_packagedata with hash ee29483d3bbb3d83e14898c2316c81ab
 changed to
openembedded-core/meta/recipes-graphics/xorg-app/xrandr_1.4.3.bb.do_packagedata with hash 0c39e999928942dfd8a7f4b8e67446d7
meta-openembedded/meta-oe/recipes-graphics/xserver-common/xserver-common_1.34.bb.do_package with hash 1657fdd755ae7b98394b34c5e29e0f6c
 changed to
meta-openembedded/meta-oe/recipes-graphics/xserver-common/xserver-common_1.34.bb.do_package with hash df6f3388166d833898c5f24024d71703
meta-openembedded/meta-oe/recipes-graphics/xserver-common/xserver-common_1.34.bb.do_packagedata with hash 2794fb1e9e3f8dd7ce2437d5396f6d49
 changed to
meta-openembedded/meta-oe/recipes-graphics/xserver-common/xserver-common_1.34.bb.do_packagedata with hash 007535177f70ddf4efae8d117226490e
Hash for dependent task xorg-appxrandr_1.4.3.bb.do_packagedata changed from ee29483d3bbb3d83e14898c2316c81ab to 0c39e999928942dfd8a7f4b8e67446d7
Hash for dependent task xinput-calibratorxinput-calibrator_git.bb.do_packagedata changed from d688277915e6c9d7e41a00d941dfc590 to 9d440e251880adaaa743aecabc86ae36
Hash for dependent task fbsetfbset_2.1.bb.do_packagedata changed from ce7c4dca0cda8d720fd74d2bd1d66fbb to a232e1b9ce0275f2a989d74cc7053a84
Hash for dependent task xserver-commonxserver-common_1.34.bb.do_package changed from 1657fdd755ae7b98394b34c5e29e0f6c to df6f3388166d833898c5f24024d71703
Hash for dependent task xorg-appxmodmap_1.0.9.bb.do_packagedata changed from 9d3e895ec99bf9e9204aa619238e4cc8 to f4a63b5a780ad1eee027ec5c41d1698b
Hash for dependent task xserver-commonxserver-common_1.34.bb.do_packagedata changed from 2794fb1e9e3f8dd7ce2437d5396f6d49 to 007535177f70ddf4efae8d117226490e
Hash for dependent task xorg-appxdpyinfo_1.3.2.bb.do_packagedata changed from 8122f0ff1b1e47cca2ddb162075e7f44 to 4d9acf7ce5cfa462d66b04b2bf14b851

ERROR: xserver-nodm-init different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'xorg-appxinit_1.3.4.bb.do_packagedata', 'xserver-commonxserver-common_1.34.bb.do_packagedata', 'xserver-nodm-initxserver-nodm-init_2.0.bb.do_package', 'xserver-nodm-initxserver-nodm-init_2.0.bb.do_packagedata'] to ['opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'xorg-appxinit_1.3.4.bb.do_packagedata', 'xserver-commonxserver-common_1.34.bb.do_packagedata', 'xserver-nodm-initxserver-nodm-init_2.0.bb.do_package', 'xserver-nodm-initxserver-nodm-init_2.0.bb.do_packagedata']
openembedded-core/meta/recipes-graphics/xorg-app/xinit_1.3.4.bb.do_packagedata with hash 6963e42ac1053b62ce4a6570a74e27bf
 changed to
openembedded-core/meta/recipes-graphics/xorg-app/xinit_1.3.4.bb.do_packagedata with hash eb81dc4aa06e4a2f1fb3e76bac3d4d88
meta-openembedded/meta-oe/recipes-graphics/xserver-common/xserver-common_1.34.bb.do_packagedata with hash 2794fb1e9e3f8dd7ce2437d5396f6d49
 changed to
meta-openembedded/meta-oe/recipes-graphics/xserver-common/xserver-common_1.34.bb.do_packagedata with hash 007535177f70ddf4efae8d117226490e
Hash for dependent task xorg-appxinit_1.3.4.bb.do_packagedata changed from 6963e42ac1053b62ce4a6570a74e27bf to eb81dc4aa06e4a2f1fb3e76bac3d4d88
Hash for dependent task xserver-commonxserver-common_1.34.bb.do_packagedata changed from 2794fb1e9e3f8dd7ce2437d5396f6d49 to 007535177f70ddf4efae8d117226490e

(From meta-openembedded rev: 9a381e8c4d4f3ce074a1f934e2f6dfc3172efe8e)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>