meta-openembedded: lftp: fix PACKAGECONFIG[readline]
The --with-readline means check readline automatically, and will cause build
failures when there is /usr/include/readline:

ERROR: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.

Use --with-readline=${STAGING_INCDIR}/.. to fix the problem. And also add
--with-readline=no when PACKAGECONFIG is not set for readline.

(From meta-openembedded rev: 06d15756bd6f77da57f527f08c9f2a3227acb3e9)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>