meta-openembedded: oscam: respect *flags set from OE
* build with -mfloat-abi=hard are failing with:
  sysroots/foo/usr/include/gnu/stubs.h:7:29: fatal error: gnu/stubs-soft.h: No such file or directory
  because cmake wasn't respecting *flags set from OE

(From meta-openembedded rev: 9f37b85bc88916aa0ac959176f77d7ce88827d0c)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>