meta-openembedded: lvm2: fix lvm2-native RRECOMMENDS problem
lvm2-native doesn't have packages, so the RRECOMMENDS must be limited
to the target case. This fixes:

ERROR: Nothing RPROVIDES 'lvm2-native-scripts-native' (but virtual:native:.../meta-openembedded/meta-oe/recipes-support/lvm2/lvm2_2.02.166.bb RDEPENDS on or otherwise requires it)

(From meta-openembedded rev: ff30e01f6200e0225ac0d03b90758b1b54712564)

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>
Signed-off-by: Peter Kjellerstedt <peter.kjellerstedt@axis.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>