meta-openembedded: inetutils: register hostname.1 man page as an alternate
The coreutils has a hostname command; this package already dealt
with that existing as an alternate, but for some reason it did not
do the same with the manpage of the same name.  The conflict varied
from intermittent to "why does this keep happening to me?!?".

Mark gets credit for the fix; he didn't want to bear witness to yet
another premature death of a USB keyboard and suggested the change
here; which I then largely just confirmed as functional, since I
happened to "be so lucky" as to have the reproducer.

The failure showed up in do_rootfs as follows:

ERROR: cube-graphical-builder-0.2-r0 do_rootfs: [log_check] cube-graphical-builder:
found 1 error message in the logfile: [log_check] update-alternatives:
Error: not linking tmp/work/qemuarm64-overc-linux/cube-graphical-builder/0.2-r0/rootfs/usr/share/man/man1/hostname.1
to /usr/share/man/man1/hostname.1.coreutils since
tmp/work/qemuarm64-overc-linux/cube-graphical-builder/0.2-r0/rootfs/usr/share/man/man1/hostname.1
exists and is not a link

Cc: Mark Hatle <mark.hatle@windriver.com>
Cc: Joe MacDonald <joe_macdonald@mentor.com>
(From meta-openembedded rev: 2418ea389b22dfbaaf7bb68ca73865a8a0292a93)

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>