meta-openembedded: libtevent: add missing dependency on libcap
The built-in library libreplace requires it,
or it fails with:
../lib/replace/system/capability.h:40:28: fatal error: sys/capability.h: No such file or directory

(From meta-openembedded rev: ad1134f299f072a4095ff2957e063f5b6376f910)

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>