meta-openembedded: glade3: Enable gnome support in meta-gnome instead of meta-oe
This decouples meta-oe dependencies on meta-gnome, right now
we have to use meta-gnome as dependent layer

ERROR: Nothing PROVIDES 'libbonoboui' (but
meta-openembedded/meta-oe/recipes-devtools/glade/glade3_3.8.2.bb
DEPENDS on or otherwise requires it)

ERROR: Required build target 'glade3' has no buildable providers.

Missing or unbuildable dependency chain was: ['glade3', 'libbonoboui']

(From meta-openembedded rev: afa3b1578f6eb75948e50e9216ae493be5b16fa8)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>