meta-openembedded: mkvtoolnix: inherit gettext and export RUBYLIB
* fails to call msgfmt in do_compile:
  MSGFMT po/cs.po
  ERROR: Function failed: do_compile (see mkvtoolnix/5.9.0-r0/temp/log.do_compile.3794 for further information)
* fails to find rubygems.rb:
  <internal:gem_prelude>:1:in `require': cannot load such file rubygems.rb (LoadError)

(From meta-openembedded rev: 5fc511458b189649197cc11680e91a2610d68415)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>