glib-2.0: fix a compilation issue due to dtrace
With multilib & x32 builds dtrace is getting turned-on by the glib-2.0
configure, which causes following compilation failure.

| x86_64-linux-libtool: link: ccache gcc
-isystem/disk0/pokybuild/build-multilib/tmp/sysroots/x86_64-linux/usr/include
-O2 -pipe -Wall -Wl,-rpath-link
-Wl,/disk0/pokybuild/build-multilib/tmp/sysroots/x86_64-linux/usr/lib
-Wl,-rpath
-Wl,/disk0/pokybuild/build-multilib/tmp/sysroots/x86_64-linux/usr/lib
-Wl,-O1 -o .libs/gtester gtester.o
-L/disk0/pokybuild/build-multilib/tmp/sysroots/x86_64-linux/usr/lib
./.libs/libglib-2.0.so -lrt -Wl,-rpath
-Wl,/disk0/pokybuild/build-multilib/tmp/sysroots/x86_64-linux/usr/lib
| ./.libs/libglib-2.0.so: undefined reference to `GLIB_SLICE_ALLOC'
| ./.libs/libglib-2.0.so: undefined reference to `GLIB_MEM_REALLOC'
| ./.libs/libglib-2.0.so: undefined reference to `GLIB_SLICE_FREE'
| ./.libs/libglib-2.0.so: undefined reference to `GLIB_MEM_ALLOC'
| ./.libs/libglib-2.0.so: undefined reference to `GLIB_MEM_FREE'
| ./.libs/libglib-2.0.so: undefined reference to `GLIB_QUARK_NEW'
| collect2: ld returned 1 exit status
| make[4]: *** [gtester] Error 1

(From OE-core rev: 482519c984a1b9da61b8b3cc97a6d28309b3192f)

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>