meta-openembedded: goffice: add patch to use pcre_fullinfo instead of pcre_info
* pcre_info was removed in newer pcre and abiword now fails to build
  /usr/lib/libgoffice-0.8.so: undefined reference to pcre_info

(From meta-openembedded rev: d1eb834bd0dc554fa9062b60a43655086b88aadb)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>