meta-openembedded: ndisc6: allow the package can be empty
FILES_${PN} is set to null in original .bb file, this would cause
ndisc6 main package is missing, then one build error will happen:

ERROR: ndisc6 not found in the base feeds (qemux86 i586 x86 noarch any all).

To fix this, need to set ALLOW_EMPTY_${PN} = "1".

(From meta-openembedded rev: 182c235bd97cfeda861fccda3634104a61bf5e79)

Signed-off-by: Xudong.zhu <xudong.zhu@windriver.com>
Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Joe MacDonald <joe@deserted.net>