meta-openembedded: lmsensors: drop LINUX=${STAGING_KERNEL_DIR} from EXTRA_OEMAKE
* it builds fine without it, STAGING_KERNEL_DIR depends on MACHINE and
  would cause whole recipe (and everything depending on it) MACHINE_ARCH
* there wasn't any kernel dependency, so STAGING_KERNEL_DIR was
  potentially empty anyway, there is no change shown in buildhistory
* nothing in lmsensors is using LINUX variable:
  OE @ ~/build/oe-core/tmp-glibc/work/i586-oe-linux/lmsensors/3.4.0-r0 $ grep -R LINUX .
  grep: ./packages-split/lmsensors-libsensors-dev/usr/lib/libsensors.so: No such file or directory
  grep: ./pseudo/pseudo.socket: No such device or address
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: lmsensors different signature for task do_configure.sigdata between qemux86copy and qemux86
basehash changed from 25ea9d362a28aa9ec283114e5793832e to c292324f876baec39dda79cb21ec969c
Variable MACHINE value changed from 'qemux86copy' to 'qemux86'

ERROR: openlmi-networking different signature for task do_configure.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['autoconfautoconf_2.69.bb.do_populate_sysroot:virtual:native', 'automakeautomake_1.15.bb.do_populate_sysroot:virtual:native', 'cim-schemacim-schema-exper_2.39.0.bb.do_populate_sysroot', 'cmakecmake-native_3.3.1.bb.do_populate_sysroot', 'dbusdbus_1.8.20.bb.do_populate_sysroot', 'gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glib-2.0glib-2.0_2.44.1.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'gnu-configgnu-config_git.bb.do_populate_sysroot:virtual:native', 'konkretcmpikonkretcmpi_0.9.2.bb.do_populate_sysroot', 'libchecklibcheck_0.10.0.bb.do_populate_sysroot', 'libtoollibtool-cross_2.4.6.bb.do_populate_sysroot', 'libtoollibtool-native_2.4.6.bb.do_populate_sysroot',
'networkmanagernetworkmanager_1.0.4.bb.do_populate_sysroot', 'openlmiopenlmi-networking_0.3.1.bb.do_generate_toolchain_file', 'openlmiopenlmi-networking_0.3.1.bb.do_patch', 'openlmiopenlmi-providers_0.6.0.bb.do_populate_sysroot', 'sblim-cmpi-develsblim-cmpi-devel_2.0.3.bb.do_populate_sysroot']
to
['autoconfautoconf_2.69.bb.do_populate_sysroot:virtual:native', 'automakeautomake_1.15.bb.do_populate_sysroot:virtual:native', 'cim-schemacim-schema-exper_2.39.0.bb.do_populate_sysroot', 'cmakecmake-native_3.3.1.bb.do_populate_sysroot', 'dbusdbus_1.8.20.bb.do_populate_sysroot', 'gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glib-2.0glib-2.0_2.44.1.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'gnu-configgnu-config_git.bb.do_populate_sysroot:virtual:native', 'konkretcmpikonkretcmpi_0.9.2.bb.do_populate_sysroot', 'libchecklibcheck_0.10.0.bb.do_populate_sysroot', 'libtoollibtool-cross_2.4.6.bb.do_populate_sysroot', 'libtoollibtool-native_2.4.6.bb.do_populate_sysroot',
'networkmanagernetworkmanager_1.0.4.bb.do_populate_sysroot', 'openlmiopenlmi-networking_0.3.1.bb.do_generate_toolchain_file', 'openlmiopenlmi-networking_0.3.1.bb.do_patch', 'openlmiopenlmi-providers_0.6.0.bb.do_populate_sysroot', 'sblim-cmpi-develsblim-cmpi-devel_2.0.3.bb.do_populate_sysroot']
meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-providers_0.6.0.bb.do_populate_sysroot with hash 669fc52398649d64161a4848e6d1903f
 changed to
meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-providers_0.6.0.bb.do_populate_sysroot with hash 8bb7a9a90ebe53c8c3d957ef7715b6e7
Hash for dependent task openlmiopenlmi-providers_0.6.0.bb.do_populate_sysroot changed from 669fc52398649d64161a4848e6d1903f to 8bb7a9a90ebe53c8c3d957ef7715b6e7

ERROR: openlmi-providers different signature for task do_configure.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['autoconfautoconf_2.69.bb.do_populate_sysroot:virtual:native', 'automakeautomake_1.15.bb.do_populate_sysroot:virtual:native', 'cim-schemacim-schema-exper_2.39.0.bb.do_populate_sysroot', 'cmakecmake-native_3.3.1.bb.do_populate_sysroot', 'dbusdbus_1.8.20.bb.do_populate_sysroot', 'gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'gnu-configgnu-config_git.bb.do_populate_sysroot:virtual:native', 'konkretcmpikonkretcmpi-native_0.9.2.bb.do_populate_sysroot', 'konkretcmpikonkretcmpi_0.9.2.bb.do_populate_sysroot', 'libtoollibtool-cross_2.4.6.bb.do_populate_sysroot', 'libtoollibtool-native_2.4.6.bb.do_populate_sysroot', 'libuserlibuser_0.62.bb.do_populate_sysroot',
'lm_sensorslmsensors_3.4.0.bb.do_populate_sysroot', 'openlmiopenlmi-providers_0.6.0.bb.do_generate_toolchain_file', 'openlmiopenlmi-providers_0.6.0.bb.do_patch', 'pciutilspciutils_3.3.1.bb.do_populate_sysroot', 'sblim-cmpi-develsblim-cmpi-devel_2.0.3.bb.do_populate_sysroot', 'sblim-sfcbsblim-sfcb_1.4.8.bb.do_populate_sysroot', 'swigswig_3.0.6.bb.do_populate_sysroot', 'swigswig_3.0.6.bb.do_populate_sysroot:virtual:native', 'systemdsystemd-systemctl-native.bb.do_populate_sysroot', 'systemdsystemd_225.bb.do_populate_sysroot']
to
['autoconfautoconf_2.69.bb.do_populate_sysroot:virtual:native', 'automakeautomake_1.15.bb.do_populate_sysroot:virtual:native', 'cim-schemacim-schema-exper_2.39.0.bb.do_populate_sysroot', 'cmakecmake-native_3.3.1.bb.do_populate_sysroot', 'dbusdbus_1.8.20.bb.do_populate_sysroot', 'gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'gnu-configgnu-config_git.bb.do_populate_sysroot:virtual:native', 'konkretcmpikonkretcmpi-native_0.9.2.bb.do_populate_sysroot', 'konkretcmpikonkretcmpi_0.9.2.bb.do_populate_sysroot', 'libtoollibtool-cross_2.4.6.bb.do_populate_sysroot', 'libtoollibtool-native_2.4.6.bb.do_populate_sysroot', 'libuserlibuser_0.62.bb.do_populate_sysroot',
'lm_sensorslmsensors_3.4.0.bb.do_populate_sysroot', 'openlmiopenlmi-providers_0.6.0.bb.do_generate_toolchain_file', 'openlmiopenlmi-providers_0.6.0.bb.do_patch', 'pciutilspciutils_3.3.1.bb.do_populate_sysroot', 'sblim-cmpi-develsblim-cmpi-devel_2.0.3.bb.do_populate_sysroot', 'sblim-sfcbsblim-sfcb_1.4.8.bb.do_populate_sysroot', 'swigswig_3.0.6.bb.do_populate_sysroot', 'swigswig_3.0.6.bb.do_populate_sysroot:virtual:native', 'systemdsystemd-systemctl-native.bb.do_populate_sysroot', 'systemdsystemd_225.bb.do_populate_sysroot']
meta-openembedded/meta-oe/recipes-support/lm_sensors/lmsensors_3.4.0.bb.do_populate_sysroot with hash 54e712e3cb33bb71e3dffd37fef1f711
 changed to
meta-openembedded/meta-oe/recipes-support/lm_sensors/lmsensors_3.4.0.bb.do_populate_sysroot with hash 4bb2920a72bc6dcdce21bd8944a0e883
Hash for dependent task lm_sensorslmsensors_3.4.0.bb.do_populate_sysroot changed from 54e712e3cb33bb71e3dffd37fef1f711 to 4bb2920a72bc6dcdce21bd8944a0e883

ERROR: openlmi-storage different signature for task do_configure.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['cmpi-bindingscmpi-bindings_git.bb.do_populate_sysroot', 'gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'openlmiopenlmi-providers_0.6.0.bb.do_populate_sysroot', 'openlmiopenlmi-storage_0.8.1.bb.do_patch', 'pythonpython-native_2.7.9.bb.do_populate_sysroot', 'pythonpython-setuptools_18.2.bb.do_populate_sysroot:virtual:native', 'pythonpython_2.7.9.bb.do_populate_sysroot', 'pywbempywbem_0.8.0.bb.do_populate_sysroot']
to
['cmpi-bindingscmpi-bindings_git.bb.do_populate_sysroot', 'gccgcc-cross_5.2.bb.do_populate_sysroot', 'gccgcc-runtime_5.2.bb.do_populate_sysroot', 'glibcglibc_2.22.bb.do_populate_sysroot', 'openlmiopenlmi-providers_0.6.0.bb.do_populate_sysroot', 'openlmiopenlmi-storage_0.8.1.bb.do_patch', 'pythonpython-native_2.7.9.bb.do_populate_sysroot', 'pythonpython-setuptools_18.2.bb.do_populate_sysroot:virtual:native', 'pythonpython_2.7.9.bb.do_populate_sysroot', 'pywbempywbem_0.8.0.bb.do_populate_sysroot']
meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-providers_0.6.0.bb.do_populate_sysroot with hash 669fc52398649d64161a4848e6d1903f
 changed to
meta-openembedded/meta-oe/recipes-extended/openlmi/openlmi-providers_0.6.0.bb.do_populate_sysroot with hash 8bb7a9a90ebe53c8c3d957ef7715b6e7
Hash for dependent task openlmiopenlmi-providers_0.6.0.bb.do_populate_sysroot changed from 669fc52398649d64161a4848e6d1903f to 8bb7a9a90ebe53c8c3d957ef7715b6e7

(From meta-openembedded rev: b145a503839840c0ea43cdab5dcab3a9c6ca7f7b)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>