meta-ostro: layer.conf: introduce LOCALCONF_VERSION
Document LOCALCONF_VERSION and how to deal with it. Bumping to 2
when introducing ostro-os-development.inc would have led to the following
QA warning directly at the start of parsing:

   ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
       Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
       Following is the list of potential problems / advisories:

       Your version of local.conf was generated from an older/newer version of local.conf.sample and there have been updates made to this file. Please compare the two files and merge any changes before continuing.
    Matching the version numbers will remove this message.
    "meld conf/local.conf ..../meta*/conf/local.conf.sample" is a good way to visualise the changes.

Now it is either too late and/or the explicit QA check deals with it,
so the version is left unchanged.

(From meta-ostro rev: be598d7b4bc11a7c9d03413f81aefcd9ae2e5fe2)

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>