meta-openembedded: rp-pppoe: Fix rootfs creation errors
error: file /usr/share/doc/README from install of rp-pppoe-doc-3.11-*
conflicts with file from package dmidecode-doc-2.12*

(From meta-openembedded rev: abc6e4965e758074b6ceb1f39809bb91c177ba95)

Signed-off-by: Li Xin <lixin.fnst@cn.fujitsu.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>