meta-intel: meta-intel/common: Fix build issues for openssl-qat-module
openssl-qat-module and zlib-qat-module recipes have the same
kernel module name, which causes the build to fail.

This fixes Bug 4126 - Crystal Forest build failing for openssl-qat-module

ERROR: Recipe openssl-qat-module is trying to create package
kernel-module-qat-mem which was already written by recipe zlib-qat-module.
This will cause corruption, please resolve this and only provide the package
from one recipe or the other or only build one of the recipes.
ERROR: Function failed: read_subpackage_metadata
ERROR: Execution of event handler 'run_buildstats' failed

(From meta-intel rev: 294487ac822b0c9b9f4ff7861c0b67b43e99a781)

Signed-off-by: Kishore Bodke <kishore.k.bodke@intel.com>