meta-openembedded: xserver-nodm-init-2.0: Remove recipe
The version in oe-core should now do everything this one does with one
exception: it does not RDEPEND on xserver-common. This dependency now
needs to be set explicitly.

(From meta-openembedded rev: 877e52fd75c7d3b88add94691df3beb5e0c54529)

Signed-off-by: Jussi Kukkonen <jussi.kukkonen@intel.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>