meta-openembedded: samba: update documentation2.patch to apply
* fails here because of non-ASCII characters:
ERROR: Command Error: exit status: 1  Output:
Applying patch documentation2.patch
patching file docs-xml/manpages-3/nmbd.8.xml
patching file docs-xml/manpages-3/samba.7.xml
patching file docs-xml/manpages-3/smb.conf.5.xml
patching file docs-xml/manpages-3/smbd.8.xml
patching file docs-xml/using_samba/appd.xml
patching file docs-xml/using_samba/ch01.xml
patching file docs-xml/using_samba/ch07.xml
patching file docs/htmldocs/manpages/nmbd.8.html
patching file docs/htmldocs/manpages/samba.7.html
patching file docs/htmldocs/manpages/smb.conf.5.html
patching file docs/htmldocs/manpages/smbd.8.html
patching file docs/manpages/nmbd.8
patching file docs/manpages/samba.7
patching file docs/manpages/smb.conf.5
patching file docs/manpages/smbd.8
patching file examples/tridge/smb.conf
patching file swat/lang/tr/help/welcome.html
Hunk #1 FAILED at 40.
Hunk #2 succeeded at 66 with fuzz 2.
1 out of 2 hunks FAILED -- rejects in file swat/lang/tr/help/welcome.html
Patch documentation2.patch does not apply (enforce with -f)
ERROR: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /OE/jansa-test/shr-core/tmp-eglibc/work/armv4t-oe-linux-gnueabi/samba-3.6.8-r0/temp/log.do_patch.2937

(From meta-openembedded rev: 1571c2c566c51799eceea2aabe13d1c3116f36b3)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>