python-scons-native: fix invoking scons failed on Fedora-17
While the destro didn't install scons, build scons by python-scons-native,
and invoke it with the error:
...
$scons -h
Traceback (most recent call last):
  File "/buildarea2/hongxujia/build-20130520-udev-emenlow/tmp/sysroots/x86_64-linux/usr/bin/scons", line 188, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
...

1, While building scons as default, scons's lib will be install in the dir of
`scons' or `scons-2.3.0' if the option `--install-lib' is not set explicitly.

2, While build python-scons-native, `--install-lib' is explicitly set, and
scons's lib was not installed in the dir of `scons' or `scons-2.3.0'.

3, While invoke scons-native, the scons searches the lib in ${STAGING_DIR_HOST}/
${PYTHON_SITEPACKAGES_DIR}/scons, ${STAGING_DIR_HOST}/${PYTHON_SITEPACKAGES_DIR}/
scons-2.3.0 rather than ${STAGING_DIR_HOST}/${PYTHON_SITEPACKAGES_DIR}.

Use create_wrapper to relocate scons-native to add `${STAGING_DIR_HOST}/${PYTHON
_SITEPACKAGES_DIR}' to PYTHONPATH, so scons-native could find out the lib.

[YOCTO #4562]

(From OE-core rev: 1aa828d05ae1614689542c6a9ce6425a088bdc7d)

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>