meta-java: jikes: fix absolute symlink error
The following oe-core commit made asbolute symlink an error:

commit 3eee8e99e114b3db8b718834ca52da8d2919b83f
sstate: Make absolute symlinks an error

Fix this by inheritting relative_symlinks class:
ERROR: jikes-native-1.22-r0 do_populate_sysroot: sstate found an
absolute path symlink

(From meta-java rev: a8e6753b5912afe7fe273a76a919a20db2d713c7)

Signed-off-by: Maxin B. John <maxin.john@intel.com>