meta-openembedded: atftp: build with gcc 5.2
atftp fails to build with gcc 5.2:

git/tftp_def.h:54:14: warning: inline function 'Strncpy' declared but never defined
git/argz.c:44:8: error: redefinition of 'argz_next'

GCC 5 defaults to -std=gnu11 instead of -std=gnu89. The semantics of
inline function changes. Pass '-std=gnu89' to gcc to compile atftp.

Ref:
https://gcc.gnu.org/gcc-5/porting_to.html

(From meta-openembedded rev: 28233847aa0f0a12f01da4782ab5b3ffefab51cd)

Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>