meta-openembedded: ckermit: update SRC_URI
it seems ftp does not work. changing to http.

WARNING: Failed to fetch URL ftp://ftp.kermitproject.org/kermit/archives/cku302.tar.gz;subdir=ckermit-302, attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 4, no output
ERROR: Function failed: Fetcher failure for URL: 'ftp://ftp.kermitproject.org/kermit/archives/cku302.tar.gz;subdir=ckermit-302'. Unable to fetch URL from any source.

(From meta-openembedded rev: 1a3d9a8ef47d0cc9d038ad218a42d5fadba106d2)

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>