meta: glib-2.0: don't apply qsort_r test removable patch for native version
On some buildhosts with an older version of native glib-2.0 installed (in this case
2.16.6) the qsort_r test removable patch leads to a compilation error:

| ./.libs/libglib-2.0.so: undefined reference to `qsort_r'
| collect2: ld returned 1 exit status

This patch fixes this so the patch gets only applied for the native version of this
recipe.

(From OE-core rev: 37579d7d74d127c90c1e078d05c5bf4ba0b3f755)

Signed-off-by: Simon Busch <morphis@gravedo.de>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>