meta-openembedded: ltp-ddt: Fix build break with newer kernels
We need to point KERNEL_INC at include-generic otherwise
we end up with errors like

|                  from src/parser/st_i2c_parser.c:42:
|
/home/kraj/work/angstrom-2013.12/build/tmp-angstrom_v2013_12-eglibc/sysroots/beaglebone/usr/src/kernel/include/linux/wait.h:8:25:
fatal error: asm/current.h: No such file or directory
|  #include <asm/current.h>
|                          ^
| compilation terminated.
| make[2]: *** [i2c_tests] Error 1

(From meta-openembedded rev: 1f89f0a54e85e540e50bb00305b4163e13b1b4dc)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>