meta-ostro: ostro-image.bb: disable IMA images if IMA config is missing
Previous attempts to build images without configure IMA
signing keys led to an error during image building:

   | install: cannot stat 'IMA_EVM_KEY_DIR_NOT_SET/x509_ima.der': No such file or directory
   | WARNING: exit code 1 from a shell command.
   | DEBUG: Python function do_image finished
   | ERROR: Function failed: ima_evm_sign_rootfs (log file is located at ....

Now such an attempt will produce a more meaningful error
message right after parsing the recipes:

   $ bitbake ostro-image-minimal
   Loading cache...done.
   Loaded 2553 entries from dependency cache.
   Parsing recipes...done.
   Parsing of 1952 .bb files complete (1951 cached, 1 parsed). 2552 targets, 1266 skipped, 2 masked, 0 errors.
   ERROR: Nothing PROVIDES 'ostro-image-minimal'
   ERROR: ostro-image-minimal was skipped:
   IMA_EVM_X509 is not set to the name of an existing file.
   Check whether IMA signing is configured correctly, see
   doc/howtos/building-images.rst.

   IMA_EVM_KEY_DIR = "IMA_EVM_KEY_DIR_NOT_SET"
   IMA_EVM_PRIVKEY = "IMA_EVM_KEY_DIR_NOT_SET/privkey_ima.pem"
   IMA_EVM_X509 = "IMA_EVM_KEY_DIR_NOT_SET/x509_ima.der"
   IMA_EVM_ROOT_CA = ""

The error check could also have been done in
meta-intel-iot-security. It was added here because then the error
message can refer to official instructions related to the actual
images.

(From meta-ostro rev: 0bdc1331114df1be74167dce0662fdb5643e8355)

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>