meta-openembedded: claws-mail: Add missing libgcrypt dependency
* otherwise fails with:
  | claws-mail/3.9.0-r0/claws-mail-3.9.0/src/common/ssl.c:35:20:
    fatal error: gcrypt.h: No such file or directory
  |  #include <gcrypt.h>

(From meta-openembedded rev: 555b3d6e3dc2703297014f161789ea932f71fa54)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>