at: fix for parallel build issue & bug #180
parallel build was failing inconsistently due to missing dependancy
specification in the make file. Fixed it with a new patch.

Bug 180 reported this issue:
| arm-poky-linux-gnueabi-gcc -march=armv5te -mtune=arm926ej-s -c -I.
-fexpensive-optimizations -fomit-frame-pointer -frename-registers -O2
-ggdb
-feliminate-unused-debug-types -DHAVE_CONFIG_H -DVERSION=\"3.1.12\"
-DETCDIR=\"/etc\" -DLOADAVG_MX=0.8 -DDAEMON_USERNAME=\"daemon\"
-DDAEMON_GROUPNAME=\"daemon\" -DLFILE=\"/var/spool/cron/atjobs/.SEQ\"
-Wall
atd.c
| atd.c:511:2: error: #error "No mail command specified."
| make: *** [atd.o] Error 1

Fixed it with the recommended solution of defining SENDMAIL as /bin/true

Fixes [BUGID #180]

Reorganized the recipe file for cleanlyness.
Add the init script for at

As per Scott's wiki instructions added the this init script for at:
http://git.buildroot.net/buildroot/tree/package/at/S99at

add libpam to dependancy
And bumped PR.

(From OE-core rev: 2eeb0943ac5b3d8f942ae7f9cf655c12827483ae)

Signed-off-by: Nitin A Kamble <nitin.a.kamble@intel.com>