meta-openembedded: vboxguestdrivers: make sure that do_compile fails when some module failed to build
* otherwise we get the failure from do_install with useless log:
  DEBUG: Executing shell function do_install
  install: cannot stat 'vboxsf.ko': No such file or directory
  WARNING: exit code 1 from a shell command.
* instead of the real issue like 5.1.14 currently has with default linux-yocto
  version:
  CC [M]  qemux86-oe-linux/vboxguestdrivers/5.1.14-r0/vbox_module/vboxsf/lnkops.o
          qemux86-oe-linux/vboxguestdrivers/5.1.14-r0/vbox_module/vboxsf/lnkops.c:93:23: error: 'generic_readlink' undeclared here (not in a function)
     .readlink       = generic_readlink,
                       ^~~~~~~~~~~~~~~~

(From meta-openembedded rev: a9715573c0e5946a35beaa1b928d9ea95bc3833d)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>