meta-openembedded: openmotif: remove due to lack of libxp in repository
ERROR: Nothing PROVIDES 'libxp' (but /home/hrw/HDD/devel/canonical/aarch64/meta-openembedded/meta-oe/recipes-support/openmotif/openmotif_2.3.3.bb DEPENDS on or otherwise requires it)
ERROR: Required build target 'openmotif' has no buildable providers.

(From meta-openembedded rev: 14b68506078a4133e743491d35245775a58a1317)

Signed-off-by: Marcin Juszkiewicz <marcin.juszkiewicz@linaro.org>