meta-ostro: ostro.conf: exclude swupd-server from world
Skip swupd-server from world build because of a build failure. Only
swupd-server-native is used so this is a safe choice.

The failure is:

configure.ac:15: error: possibly undefined macro: AC_MSG_ERROR
       If this token and others are legitimate, please use m4_pattern_allow.
       See the Autoconf documentation.
configure.ac:20: error: possibly undefined macro: AS_IF
ERROR: autoreconf execution failed.

(From meta-ostro rev: fbb0baf3e6ce5a2f3ea2940fc022f4fa7b2cd0ba)

Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>