meta-openembedded: efibootmgr: fix build error with gcc 5.2
It fails to build efibootmgr with gcc 5.2:

src/lib/disk.o: In function `disk_get_scsi_pci':
src/lib/disk.c:154: undefined reference to `get_scsi_pci'
src/lib/efi.o: In function `make_edd30_device_path':
src/lib/efi.c:474: undefined reference to `get_scsi_idlun'
collect2: error: ld returned 1 exit status

Because functions get_scsi_pci and get_scsi_idlun are declared as
inline. It has different semantics for inilne function between gcc 4
and gcc 5.

Pass flag '-fgnu89-inline' to gcc to fix the errors.

Ref:
https://gcc.gnu.org/gcc-5/porting_to.html

(From meta-openembedded rev: b1bdecb7be72b2acff63d6b8581d79c9d79661be)

Signed-off-by: Kai Kang <kai.kang@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>