meta-openembedded: sblim-sfcb: add missing dependency on unzip-native
* otherwise configure fails with:
  | checking whether to build shared libraries... yes
  | checking whether to build static libraries... no
  | checking for unzip... no
  | configure: error: Could not find unzip
  | NOTE: The following config.log files may provide further information.
  | NOTE: /home/jenkins/oe/world/shr-core/tmp-glibc/work/armv5te-oe-linux-gnueabi/sblim-sfcb/1.4.9-r0/build/config.log
  | ERROR: configure failed
  | ERROR: Function failed: do_configure (log file is located at /home/jenkins/oe/world/shr-core/tmp-glibc/work/armv5te-oe-linux-gnueabi/sblim-sfcb/1.4.9-r0/temp/log.do_configure.9838)
  NOTE: recipe sblim-sfcb-1.4.9-r0: task do_configure: Failed
  ERROR: Task 5 (/home/jenkins/oe/world/shr-core/meta-openembedded/meta-oe/recipes-extended/sblim-sfcb/sblim-sfcb_1.4.9.bb, do_configure) failed with exit code '1'

(From meta-openembedded rev: 1bd027eba40546dcf1eaa02c518cad3c0495b34f)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>