meta-openembedded: lmsensors: exclude lmsensors-config dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: lmsensors different signature for task do_package_write_ipk.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['bashbash_4.3.30.bb.do_packagedata', 'lm_sensorslmsensors-config_1.0.bb.do_packagedata', 'lm_sensorslmsensors_3.4.0.bb.do_package', 'lm_sensorslmsensors_3.4.0.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'perlperl_5.22.0.bb.do_packagedata', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'rrdtoolrrdtool_1.5.4.bb.do_packagedata'] to ['bashbash_4.3.30.bb.do_packagedata', 'lm_sensorslmsensors-config_1.0.bb.do_packagedata', 'lm_sensorslmsensors_3.4.0.bb.do_package', 'lm_sensorslmsensors_3.4.0.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'perlperl_5.22.0.bb.do_packagedata', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'rrdtoolrrdtool_1.5.4.bb.do_packagedata']
meta-openembedded/meta-oe/recipes-support/lm_sensors/lmsensors-config_1.0.bb.do_packagedata with hash 26762e381db19859b96a0c8ce13ee808
 changed to
meta-openembedded/meta-oe/recipes-support/lm_sensors/lmsensors-config_1.0.bb.do_packagedata with hash a94903117ba4beac7f22a4edd3084d9b
Hash for dependent task lm_sensorslmsensors-config_1.0.bb.do_packagedata changed from 26762e381db19859b96a0c8ce13ee808 to a94903117ba4beac7f22a4edd3084d9b

(From meta-openembedded rev: d70899b30f7acea4eba3870bbe14a37a44ea7528)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>