meta-openembedded: packagekit: Fix build with new glib-2.0
Fixes errors like

| pk-main.c:223: error: undefined reference to 'g_thread_supported'
| collect2: error: ld returned 1 exit status
| make[3]: *** [packagekitd] Error 1

This version is dead upstream so this patch is local

(From meta-openembedded rev: 006ce59b7b1d8b77fddc1273ba53ad7d535f3ff1)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>