meta-openembedded: gtksourceview2: fix build with gcc6
Fix build error:
../../gtksourceview-2.10.5/gtksourceview/gtksourceprintcompositor.c:
In function 'strdup_strftime':
../../gtksourceview-2.10.5/gtksourceview/gtksourceprintcompositor.c:1951:3:
error: format not a string literal, format string not checked [-Werror=format-nonliteral]
   tmplen = strftime (tmpbuf, tmpbufsize, locale_format, tm);
   ^~~~~~

A wrapper for strftime() would compile failed with -Werror=format-nonliteral
in newer GCC. See GCC bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=39438

Since most of the strdup_strftime function code is taken from GLib's
g_date_strftime() in gdate.c which already had a fix:
https://bugzilla.gnome.org/show_bug.cgi?id=761550

So this patch refers the glib fixes:
https://git.gnome.org/browse/glib/commit/?id=0817af40e8c74c721c30f6ef482b1f53d12044c7
https://git.gnome.org/browse/glib/commit/?id=8cdbc7fb2c8c876902e457abe46ee18a0b134486

(From meta-openembedded rev: ca363445b80b47f3e0c18cb9d96b9463ce86b913)

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>