meta-openembedded: vim: don't check acl header if acl support disabled
Vim/vim-tiny always check 'sys/acl.h' existence even acl support
has been disabled from configure line. This works in mostly time
but except for acl works in an odd mode - while acl was mirrored
from sstate_cache, it will install 'sys/acl.h' to sysroot dir and
and then clean the header file with sysroot_cleansstate().

If build vim/vim-tiny and acl in parallel, below errors will occur:

* os_unix.c:2668:23: fatal error: sys/acl.h: No such file or directory

This change only workaround the failure and get build running, we
still need to fix it from acl side.

(From meta-openembedded rev: 38d45f7446d845b9c19367d7b17c4625537a1101)

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>
Signed-off-by: Chong Lu <Chong.Lu@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>