meta-openembedded: samba: add PACKAGECONFIG for valgrind
* Add configure options '--without-valgrind'
* Disable valgrind by default since it doesn't build for all targets

This fixes build errors:

  ../source3/include/includes.h:156:31: fatal error: \
    valgrind/memcheck.h: No such file or directory
  compilation terminated.

(From meta-openembedded rev: 71cebad9798894a9aac19577c1a1a6a08046390b)

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>