meta-openembedded: rrdtool: fix multilib problem
When building rrdtool with multilib enabled, we would meet the following error.

ERROR: QA Issue: rrdtool: Files/directories were installed but not shipped in any package:
  /usr/lib
  /usr/lib/python2.7
  /usr/lib/python2.7/site-packages
  /usr/lib/python2.7/site-packages/rrdtool.so
  ....

Fix this problem by using nonarch_libdir instead of libdir.

(From meta-openembedded rev: ff477aa4e6199b3433ab315a5533ed89f09ad9c9)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>