meta-openembedded: gnome-keyring: Turn off QA check dev-elf
The ${PN}-dev part of the recipe intentionally adds several .so files
which are used for development.

The latest OE will fail as follows building the package as a result.

ERROR: gnome-keyring-2.32.1-r12 do_package_qa: QA Issue: -dev package contains non-symlink .so: gnome-keyring-dev path '/work/core2-64-oe-linux/gnome-keyring/2.32.1-r12/packages-split/gnome-keyring-dev/usr/lib64/gnome-keyring/devel/gkm-ssh-store-standalone.so'
-dev package contains non-symlink .so: gnome-keyring-dev path '/work/core2-64-oe-linux/gnome-keyring/2.32.1-r12/packages-split/gnome-keyring-dev/usr/lib64/gnome-keyring/devel/gkm-user-store-standalone.so' [dev-elf]
ERROR: gnome-keyring-2.32.1-r12 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: gnome-keyring-2.32.1-r12 do_package_qa: Function failed: do_package_qa
ERROR: Logfile of failure stored in: /git/core/build-intel-x86/tmp/work/core2-64-oe-linux/gnome-keyring/2.32.1-r12/temp/log.do_package_qa.14188
ERROR: Task (/git/core/layers/meta-openembedded/meta-gnome/recipes-gnome/gnome-keyring/gnome-keyring_2.32.1.bb:do_package_qa) failed with exit code '1'

(From meta-openembedded rev: cfbbe3f1834ba80800f8f529621223ca4cba9c17)

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>