meta-openembedded: system-config-keyboard: inherit gettext and add dependency on intltool-native
* it actually depends on native intltool:
  NOTE: recipe system-config-keyboard-1.4.0-r0: task do_compile: Started
  ERROR: system-config-keyboard-1.4.0-r0 do_compile: oe_runmake failed
  ERROR: system-config-keyboard-1.4.0-r0 do_compile: Function failed: do_compile (log file is located at /home/jenkins/oe/world/shr-core/tmp-glibc/work/armv5te-oe-linux-gnueabi/system-config-keyboard/1.4.0-r0/temp/log.do_compile.16052)
  ERROR: Logfile of failure stored in: /home/jenkins/oe/world/shr-core/tmp-glibc/work/armv5te-oe-linux-gnueabi/system-config-keyboard/1.4.0-r0/temp/log.do_compile.16052
  Log data follows:
  | DEBUG: Executing shell function do_compile
  | NOTE: make -j 8 PYTHON=/home/jenkins/oe/world/shr-core/tmp-glibc/sysroots/x86_64-linux/usr/bin/python-native/python PYTHON_SITELIB=/usr/lib/python2.7/site-packages
  | make: intltool-merge: Command not found
  | make: *** [system-config-keyboard.desktop] Error 127
  | ERROR: oe_runmake failed
  | ERROR: Function failed: do_compile (log file is located at /home/jenkins/oe/world/shr-core/tmp-glibc/work/armv5te-oe-linux-gnueabi/system-config-keyboard/1.4.0-r0/temp/log.do_compile.16052)
  NOTE: recipe system-config-keyboard-1.4.0-r0: task do_compile: Failed
* and it also used gettext:
  | DEBUG: Executing shell function do_compile
  | NOTE: make -j 8
  PYTHON=/home/jenkins/oe/world/shr-core/tmp-glibc/sysroots/x86_64-linux/usr/bin/python-native/python
  PYTHON_SITELIB=/usr/lib/python2.7/site-packages
  | cd po && for i in *.po; do msgfmt $i -o $(echo $i |sed s/.po/.mo/) ||
  exit 1; done
  | echo -e "#!/bin/sh\nexec /usr/bin/pkexec
  /usr/sbin/system-config-keyboard \"\$@\"" > "system-config-keyboard.sh"
  | chmod 755 "system-config-keyboard.sh"
  | /bin/sh: 1: msgfmt: not found
  | make: *** [gettext] Error 1
  | make: *** Waiting for unfinished jobs....
  | Merging translations into system-config-keyboard.desktop.
  | WARNING: exit code 1 from a shell command.
  | ERROR: oe_runmake failed
  | ERROR: Function failed: do_compile (log file is located at
  /home/jenkins/oe/world/shr-core/tmp-glibc/work/armv5te-oe-linux-gnueabi/system-config-keyboard/1.4.0-r0/temp/log.do_compile.23230)

(From meta-openembedded rev: 504fc47cec26704bf4a02dba5e6a0dccb46e9b39)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>