meta-openembedded: linuxptp: Use environment compiler settings
If the machine uses hard floating point, the build fails as below:

arm-oel-linux-gnueabi-gcc -Wall ...
In file included from .../build/tmp/sysroots/imx6qsabresd/usr/include/features.h:402:0,
                 from .../build/tmp/sysroots/imx6qsabresd/usr/include/errno.h:28,
                 from clock.c:19:
.../build/tmp/sysroots/imx6qsabresd/usr/include/gnu/stubs.h:7:29:
    fatal error: gnu/stubs-soft.h: No such file or directory
 # include <gnu/stubs-soft.h>

This patch fixes the build system to reuse the CC variable and also
passes over the defined CFLAGS so the choosen optimization and build
options are respected.

(From meta-openembedded rev: f52c0d42f4b87cb3cf925bed09bf116c0e4fbaaf)

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>