meta-openembedded: orbit2: cleanup recipe, merge .inc and -native
* fix LICENSE field
* this also upgrades -native from 2.14.12 to 2.14.17, because 2.14.12 is failing to
  configure:13143: checking alignment of CORBA_octet
  configure:13170: gcc -o conftest -isystem/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/include -O2 -pipe -isystem/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/include -pthread -I/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/include/glib-2.0 -I/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/lib/glib-2.0/include    -L/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/lib -L/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/lib -Wl,-rpath-link,/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/lib -Wl,-rpath-link,/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/lib -Wl,-rpath,/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/lib -Wl,-rpath,/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/lib -Wl,-O1 conftest.c -pthread -Wl,--export-dynamic -L/OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/lib -lgobject-2.0 -lgthread-2.0 -lgmodule-2.0 -lrt -lglib-2.0    >&5
  In file included from ./include/orbit/util/basic_types.h:5:0,
                   from conftest.c:45:
  /OE/shr-core/tmp-eglibc/sysroots/x86_64-linux/usr/include/glib-2.0/glib/gunicode.h:23:2: error: #error 'Only <glib.h> can be included directly.'
* use GNOME_MIRROR and SHRT_VER in SRC_URI

(From meta-openembedded rev: 7e5b1e477a25c3dc661a2c155a22022a07903d0a)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>