meta-openembedded: mariadb: Fix rootfs creation errors
error: file /usr/share/doc/README from install of mariadb-leftovers-5.5.46-*
conflicts with file from package dmidecode-doc-2.12-*

(From meta-openembedded rev: b5a7dfbea5de5315eb09235e6dcd4930fcc467da)

Signed-off-by: Li Xin <lixin.fnst@cn.fujitsu.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>