meta-openembedded: protobuf: update update and build fix
googlecode is shutting down so had to move SRC_URI to github.
changed LIC_FILES_CHKSUM to LICENSE since COPY.TXT has been removed.

updated fixed the following build issue:

| tmp/work/ppc7400-poky-linux/protobuf/2.5.0-r0/protobuf-2.5.0/src/google/protobuf/extension_set.cc:81:3: error: 'GoogleOnceInit' is not a member of 'google::protobuf'
|    ::google::protobuf::GoogleOnceInit(&registry_init_, &InitRegistry);
|    ^
| tmp/work/ppc7400-poky-linux/protobuf/2.5.0-r0/protobuf-2.5.0/src/google/protobuf/extension_set.cc:81:39: error: 'registry_init_' was not declared in this scope
|    ::google::protobuf::GoogleOnceInit(&registry_init_, &InitRegistry);
|                                        ^

(From meta-openembedded rev: bf6aa3c1eb1224caf593994d859bbb2fbb735d6c)

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>