meta-openembedded: glmark2: Fix build error due a missing space before a macro
This fixes following error:

../src/native-state-x11.cpp:63:33: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
     static const char *win_name("glmark2 "GLMARK_VERSION);

(From meta-openembedded rev: c0e0c7797065d2130f8de867fbf7501250d2b131)

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>